### ISSUE TITLE
ommiting the number for a dice crashes

### ISSUE THREAD

**Issue by Garonenur** [syntruth/Dice-Bag#5]
typing
```ruby
irb(main):021:0> puts DiceBag::Roll.new('d8').result
```
results in:
```
TypeError: can't convert nil into Integer
	from /home/dirk/Repositories/Dice-Bag/lib/dicebag/transform.rb:53:in `Integer'
	from /home/dirk/Repositories/Dice-Bag/lib/dicebag/transform.rb:53:in `block in <class:Transform>'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:216:in `instance_eval'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:216:in `call_on_match'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:234:in `block in transform_elt'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:231:in `each'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:231:in `transform_elt'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:184:in `apply'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:246:in `block in recurse_hash'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:245:in `each'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:245:in `inject'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:245:in `recurse_hash'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:187:in `apply'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:246:in `block in recurse_hash'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:245:in `each'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:245:in `inject'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:245:in `recurse_hash'
	from /home/dirk/.gem/ruby/2.1.0/gems/parslet-1.7.1/lib/parslet/transform.rb:187:in `apply'
	from /home/dirk/Repositories/Dice-Bag/lib/dicebag.rb:174:in `parse'
	from /home/dirk/Repositories/Dice-Bag/lib/dicebag/roll.rb:18:in `initialize'
	from (irb):21:in `new'
	from (irb):21
```

**Comment by syntruth** [comment]
Oops. Fixed! :)

**Comment by Garonenur** [comment]
thanks a lot
